### ISSUE TITLE
check

### ISSUE THREAD

**Issue by guillim** [cesarve77/simple-chat#5]
Hi, I was trying to set up your nice SimpleChat, when I encountered an issue on my server: 

 "Exception while invoking method 'SimpleChat.join' Error: Did not check() all arguments during call to 'SimpleChat.join'"

I went into your package, and I guess it is simply because in this file "cesarve_simple-chat.js" 
inside the function "SimpleChatNewMessage" you forget to check username ad custom. 

Would be nice to check them so that your package works :)

**Comment by cesarve77** [comment]
I'm working on that, but I wonder why this error, I now is a mistake not check the arguments.
But that no reason for throw a error.
Maybe you have some package o configuration which check this, I would like to know.

Sorry for my english,

I promise a commit i couple of hours

**Comment by cesarve77** [comment]
New commit ready.
And important security bug was fixed.
There was direct access to DB on client side

**Comment by guillim** [comment]
tks for being so fast ! I checked my error again: it comes from the a specific package. Browsing online, I found out that it was usually triggered by the package "audit-argument-checks".

I removed this package and now it works perfectly. So I guess your package is not yet compatible with this "audit-argument-checks" package (if you don't know about it, it basically helps you to check everything in order to avoid problems https://docs.meteor.com/packages/audit-argument-checks.html ). Let me know if you plan to make it compatible with "audit-argument-checks".

Cheers

**Comment by cesarve77** [comment]
Yes absolutely.

I think this new release should be compatible .

Did you update the package?

**Comment by guillim** [comment]
Yes the two packages  "audit-argument-checks" and "cesarve:simple-chat" are up to date. But I still see the same error due to the  "audit-argument-checks" package. You already worked on it ?

**Comment by cesarve77** [comment]
Yes but let me install audit-argument-checks and try again

**Comment by cesarve77** [comment]
Ready, in fact I forgotten to check one parameter, (custom parameter)
I just update the component to meteor 1.4.2, then be sure your app is update before update simplechat

cheers

**Comment by guillim** [comment]
Works good now ! 
Funny, i still see the same errors on the server-side:
"Error: Did not check() all arguments during call to 'SimpleChat.join"
and
"Error: Did not check() all arguments during call to 'SimpleChat.newMessage".

But it works fine. so congrats, the package works. If you have time in the future, it may be on your issue to be solved, but at least it won't make the package to break :)

Note: meteor 1.4.2 is my current version

**Comment by cesarve77** [comment]
Perfect thanks

**Comment by cesarve77** [comment]
Ready I find a bug,
Try again

**Comment by guillim** [comment]
Works perfectly now !!! Congrats
